export const FETCH_BUZZ='FETCH_BUZZ';
export const FETCH_ISSUETYPE='FETCH_ISSUETYPE';
export const FETCH_DEPARTMENT='FETCH_DEPARTMENT';
export const ADD_DEPARTMENT='ADD_DEPARTMENT';
export const DELETE_BUZZ='DELETE_BUZZ';
export const LIKE_BUZZ='LIKE_BUZZ';
export const DISLIKE_BUZZ='DISLIKE_BUZZ';
export const REACT_BUZZ='REACT_BUZZ';
export const CREATE_BUZZ='CREATE_BUZZ';
export const FILE_COMPLAINT='FILE_COMPLAINT';
export const FETCH_COMPLAINT='FETCH_COMPLAINT';
export const ASSIGN_COMPLAINT='ASSIGN_COMPLAINT';
export const RESOLVE_COMPLAINT='RESOLVE_COMPLAINT';
export const USER_LOGIN='USER_LOGIN';
export const FETCH_USER='FETCH_USER';



