export const FETCH_BUZZ='FETCH_BUZZ';
export const FETCH_DEPARTMENT='FETCH_DEPARTMENT';
export const ADD_DEPARTMENT='ADD_DEPARTMENT';
export const DELETE_BUZZ='DELETE_BUZZ';
export const LIKE_BUZZ='LIKE_BUZZ';
export const DISLIKE_BUZZ='DISLIKE_BUZZ';
export const CREATE_BUZZ='CREATE_BUZZ';

export const FILE_COMPLAINT='FILE_COMPLAINT';
export const FETCH_COMPLAINT='FETCH_COMPLAINT';
export const UPDATE_COMPLAINT_STATUS='UPDATE_COMPLAINT_STATUS';

export const FETCH_USER='FETCH_USER';
export const FETCH_ALL_USERS='FETCH_ALL_USERS';
export const UPLOAD_USER_PHOTO='UPLOAD_USER_PHOTO';




